spring.application.name=sap

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/document_version_control
spring.datasource.username=dvc_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=bXlzdXBlcnNlY3JldGtleW15c3VwZXJzZWNyZXRrZXlteXN1cGVyc2VjcmV0a2V5MTIzNDU2
jwt.expiration=86400000
